<a href="https://colab.research.google.com/github/kellpowell7/ph306fa26notes/blob/main/ph30608312026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from astropy import units as u, constants as consts

In [ ]:
t1 = [1, 'a', 3.]
t1
arr1 = np.array([])

In [ ]:
for elem in l1:
  print(elem) # this is called unpacking, via a metaclass called iterables (lists and tuples)
#thus if u do a for loop in an iterable, itll process the array via multithreading


In [ ]:
t1.append('type') #lists are mutable, tuples are immutable
#tuples also dont need parenthesis, python with auto assume its a tuple

In [ ]:
arr1 = np.array([[1, 4, 7, 8]], dtype ='uint8') # now its using a single byte
arr1.dtype #checks the type of the variables inside
arr1.shape

#to transpose an array add '.T' to the end of the creation statement
arr1 = np.array([[1, 4, 7, 8], [3, 4, 6, 7]])
arr1.shape

(2, 4)

In [ ]:
arr2 = np.arange(27).reshape(3, 3, 3)
arr3 = np.linspace(-1, 1) # spits out 50 linearly spaced values from -1 to 1, you can specifiy the amount of elements as well
arr4 = np.logspace(-1, 1, 51) # logarithmically spaced values, equivalent step size in powers of 10
arr5 = np.geomspace(0.1, 10, 51) # equivalent to the above line, doing the same thing in terms of values

array([ 0.1       ,  0.10964782,  0.12022644,  0.13182567,  0.14454398,
        0.15848932,  0.17378008,  0.19054607,  0.20892961,  0.22908677,
        0.25118864,  0.27542287,  0.30199517,  0.33113112,  0.36307805,
        0.39810717,  0.43651583,  0.47863009,  0.52480746,  0.57543994,
        0.63095734,  0.69183097,  0.75857758,  0.83176377,  0.91201084,
        1.        ,  1.0964782 ,  1.20226443,  1.31825674,  1.44543977,
        1.58489319,  1.73780083,  1.90546072,  2.08929613,  2.29086765,
        2.51188643,  2.7542287 ,  3.01995172,  3.31131121,  3.63078055,
        3.98107171,  4.36515832,  4.78630092,  5.2480746 ,  5.75439937,
        6.30957344,  6.91830971,  7.58577575,  8.31763771,  9.12010839,
       10.        ])

In [ ]:
arr1 = np.zeros((3, 4)) # creates a 3x4 of zeroes, 'computationally mid' - waldron
arr2 = np.empty((4, 5)) # similarly, but grabs a random section of memory without assigning values, more effecient if assigning values in the future
arr3 = np.eye(4) # --> creates a 4x4 identity matrixa
# this is quicker than doing the list.append method
# arrays can also hold things that are not simply numerical

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
rng = np.random.default_rng(0) # seeding the function gives it a repeatability
rng.normal() # gaussian distributed random vars
rng.uniform()

0.2697867137638703

In [ ]:
rng = np.random.default_rng(1000)
rng.normal(2, 0.5, size = (5, 5)).mean() # most stat functions are built into the rng commands

np.float64(1.9783055950731516)

In [ ]:
#element wise operations
arr1 = np.arange(12).reshape((3, 4))
arr2 = np.arange(-12, 0).reshape((3, 4))
print(arr1)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[-12 -11 -10  -9]
 [ -8  -7  -6  -5]
 [ -4  -3  -2  -1]]


In [ ]:
arr1 + arr2

array([[-12, -10,  -8,  -6],
       [ -4,  -2,   0,   2],
       [  4,   6,   8,  10]])

In [ ]:
arr1 // arr2 # floor division or intoger division

array([[  0,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -2],
       [ -2,  -3,  -5, -11]])

In [ ]:
arr1 = np.arange(12, dtype=float).reshape((4, 3))
arr2 = np.arange(12, dtype=float).reshape((3, 4)) + 3
arr3 = np.arange(16, dtype=float).reshape((4, 4)) + 1

print(arr1)
print(arr2)
print(arr3)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[ 3.  4.  5.  6.]
 [ 7.  8.  9. 10.]
 [11. 12. 13. 14.]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [ ]:
np.dot(arr1[0], arr2[0])

np.cross(arr1[0], arr2[0]) # cross for 0th row of each array
# remember python is row major not column major so rows are more efficient

array([-3.,  6., -3.])

In [ ]:
# matrix mult
arr1 @ arr2
arr2 @ arr1

array([[ 96., 114., 132.],
       [168., 202., 236.],
       [240., 290., 340.]])

In [ ]:
# square matrices
arr3 ** -1 # gives us a 4x4 inverse matrix
# if determinant is small with an error, the inv blows up

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.07692308, 0.07142857, 0.06666667, 0.0625    ]])

In [ ]:
np.linalg.inv(rng.normal(2, 0.5, size=(5, 5)))
np.linalg.det(rng.normal(2, 0.5, size=(5, 5)))

np.float64(5.519829650894952)

In [ ]:
np.linalg.matrix_rank(rng.normal(2, 0.5, size = (5, 5)))
# measure of how linearly independent each of the rows are

# Ax = b --> x = A^-1 b is computationally inefficient, and thus an expensive operation


np.int64(5)

In [ ]:
np.linalg.solve() # --> the proper way to do the above operation
# this uses a gaussian row reduction algorithm