<a href="https://colab.research.google.com/github/kellpowell7/ph306fa26notes/blob/main/ph30609022026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from astropy import units as u, constants as const

In [5]:
k = 1/(4*np.pi*const.eps0)

In [17]:
x = np.linspace(-1, 1, 11) * u.m
y = np.linspace(-0.5, 0.5, 5) * u.m
x, y = np.meshgrid(x, y)
r = np.sqrt(x**2 + y**2)

In [18]:
q = 1 * u.nC
V = k*q/np.sqrt(r**2 + 0.0001*u.m**2) << u.V # correction factor to avoid div0 errors

In [12]:
V

<Quantity [[8.03838917e+09, 9.52625068e+09, 1.15064378e+10,
            1.40344863e+10, 1.66865879e+10, 1.79715096e+10,
            1.66865879e+10, 1.40344863e+10, 1.15064378e+10,
            9.52625068e+09, 8.03838917e+09],
           [8.71879568e+09, 1.07222847e+10, 1.38253667e+10,
            1.90492914e+10, 2.80587116e+10, 3.59214815e+10,
            2.80587116e+10, 1.90492914e+10, 1.38253667e+10,
            1.07222847e+10, 8.71879568e+09],
           [8.98710245e+09, 1.12335622e+10, 1.49771730e+10,
            2.24618612e+10, 4.48816919e+10, 8.98755179e+11,
            4.48816919e+10, 2.24618612e+10, 1.49771730e+10,
            1.12335622e+10, 8.98710245e+09],
           [8.71879568e+09, 1.07222847e+10, 1.38253667e+10,
            1.90492914e+10, 2.80587116e+10, 3.59214815e+10,
            2.80587116e+10, 1.90492914e+10, 1.38253667e+10,
            1.07222847e+10, 8.71879568e+09],
           [8.03838917e+09, 9.52625068e+09, 1.15064378e+10,
            1.40344863e+10, 1.66865879e+

In [19]:
x = np.linspace(-1, 1, 3).reshape((1, 3))
y = np.linspace(-0.5, 0.5, 3).reshape((3, 1))
print(x) # this method of broadcasting is generally quicker than meshgrid
print(y)
print(x+y)

[[-1.  0.  1.]]
[[-0.5]
 [ 0. ]
 [ 0.5]]
[[-1.5 -0.5  0.5]
 [-1.   0.   1. ]
 [-0.5  0.5  1.5]]


In [20]:
# vars
R = 125
V = 24
# linear
A = np.array([
    [R, R, 0, -R, 0, 0],
    [0, R, -R, 0, 0, 0],
    [0, 0, 0, R, -R, 0],
    [0, 0, 1, 0, -1, -1],
    [0, 1, 0, -1, 0, 1],
    [-1, 0, 0, 1, 1, 0]
])
b = np.array([V, -V, V, 0, 0, 0])
I = np.linalg.solve(A, b)
print(I * u.A)

[0.384 0.096 0.288 0.288 0.096 0.192] A
